### ISSUE TITLE
Using black force-exclude option in pyproject.toml to exclude selected files.

### ISSUE THREAD

**Issue by Tyrn** [jidicula/pre-commit-black#1]
Hi,

I've been trying to exclude not a directory, but a set of selected files in my project's home directory. Nothing helps. Exactly my question is asked [here](https://github.com/psf/black/issues/3013). Unfortunately, the good girl forgot to post her solution.

Here is my non-working pyproject.toml:
```
[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
force-exclude = '''

(
  /(
      i2c_lcd\.py
    | lcd_api\.py
  )/
)
'''
```
I want `$ black  .` to leave alone two files `i2c_lcd.py` and `lcd_api.py` in the current directory.

**Comment by Tyrn** [comment]
Oh, this works:
```
force-exclude = '''
(
  i2c_lcd.py
  | lcd_api.py
)
'''

```
Why?

**Comment by jidicula** [comment]
It's been a while since I did anything in Python and I created this repo solely as a minimal reproducible example for an issue I was facing a couple of years ago, so I don't know the answer to your question. I do vaguely remember having to resort to the `force-exclude` solution you reached, but I'm not sure why it works.

Sorry that I can't be of more help!
